apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-peliculas-v1
  labels:
    app: api-peliculas
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-peliculas
  template:
    metadata:
      labels:
        app: api-peliculas
        version: "1.0"
    spec:
      containers:
      - name: api-peliculas
        image: mpocampod/api-peliculas:v1
        ports:
        - name: http-server
          containerPort: 5000