apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-peliculas-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-peliculas
  template:
    metadata:
      labels:
        app: postgres-peliculas
    spec:
      containers:
        - name: postgres-peliculas-v1
          image: postgres:latest
          ports:
            - containerPort: 5432  
          env:
            - name: POSTGRES_HOST
              value: suleiman.db.elephantsql.com
            - name: POSTGRES_DB
              value: koalvwnd
            - name: POSTGRES_USER
              value: koalvwnd
            - name: POSTGRES_PASSWORD
              value: clSZeSvtDEcrT-u5iq1qInt_L-2892zn