apiVersion: v1
kind: Service
metadata:
  name: postgress-peliculas-v1
  labels:
    app: postgress-peliculas
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: postgress-peliculas
  type: ClusterIP