apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-peliculas-v1
  labels:
    app: postgres-peliculas
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-peliculas
  template:
    metadata:
      labels:
        app: postgres-peliculas
        version: "1.0"
    spec:
      containers:
      - name: postgres-peliculas
        image: postgres:latest
        ports:
        - name: http-server
          containerPort: 5432